# 🐻‍❄️🔥 setup-protoc: GitHub action for setting up the Protocol Buffers compiler
# Copyright (c) 2023-2024 Noelware, LLC. <team@noelware.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Setup Protocol Buffers compiler
description: 🐻‍❄️🔥 GitHub action for setting up the Protocol Buffers compiler
author: Noelware, LLC. <team@noelware.org>

branding:
    icon: archive
    color: orange

runs:
    using: node20
    main: ./build/action.js

inputs:
    version:
        description: The version of the `protoc` compiler to use
        required: false
        default: latest

    repo-token:
        description: The token to use to avoid ratelimiting
        required: false

    include-pre-releases:
        description: If the action should install pre-releases of the `protoc` compiler
        required: false
        default: 'false'
outputs:
    binary:
        description: Binary location to where `protoc` was installed at
